import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "دفتر للاستشارات",
  description: "عمل مالي يبدو بسيطًا، حتى حين لا تكون المسألة كذلك. قوائم مالية، واستعداد للتدقيق، ومراجعة فنية، ودعم صفقات.",
};

const email="mailto:ahmad@daftaradvisory.com?subject=محادثة%20مع%20دفتر";
const services=[["٠١","القوائم المالية","إعداد أو تنظيف القوائم المالية وملفّاتها الداعمة، بصيغة تصمد أمام التدقيق."],["٠٢","الاستعداد للتدقيق","مساعدة قبل وصول المدقّق، ليجري التدقيق أسرع وبضغط أقل: مراجعة فجوات، قائمة مستندات، خطة معالجة."],["٠٣","المراجعة الفنية","رأي ثانٍ مستقلّ في رقم أو مذكّرة أو معالجة أو موقف محاسبي، مع تعليقات مكتوبة وخطوات عملية."],["٠٤","دعم الصفقات","دعم مركّز حول الصفقات والمشاريع الخاصة — مهمّات محدّدة، لا استشارات مفتوحة."]];
const fit=[["تتحدّث إلى من ينجز العمل","وصول مباشر إلى الممارس الأقدم، لا طبقات وسيطة."],["تعرف النطاق قبل البدء","لا مفاجآت، ولا عمل مفتوح بلا حدود."],["تحصل على ملفّ عملي","مخرَج تحتفظ به، لا مجرّد تعليقات."],["تخرج بشيء يبقى","أداة يستمرّ فريقك في استخدامها بعد انتهاء المهمة."]];
function Mark(){return <Link className="brand daftar-brand" href="/ar"><b>D</b><span><em>دفتر</em><small>للاستشارات</small></span></Link>}
function Eye({children}:{children:React.ReactNode}){return <div className="eyebrow chapter"><i/>{children}</div>}
export default function DaftarAr(){return <main className="daftar ar" dir="rtl" lang="ar"><header><Mark/><nav><a href="#services">الخدمات</a><a href="#plain">بعبارة بسيطة</a><a href="#fit">المناسب</a><Link href="/ar/calibre">كاليبر</Link><Link href="/" className="lang" aria-label="English">EN</Link><a className="button small" href="#scope">ابدأ محادثة</a></nav><a className="menu" href="#services">☰</a></header>
<section className="hero wrap daftar-hero"><div><Eye>§ ٠٠ · الشركة</Eye><h1>مشورة واضحة. عمل أقدم. بلا طبقات إضافية.</h1><p className="lead">دفتر للاستشارات يساعد المؤسّسين والفِرق المالية على إنجاز أهمّ الأعمال: القوائم المالية، والاستعداد للتدقيق، والمراجعة الفنية، ودعم الصفقات.</p><a className="text-link" href="#services">اطّلع على الخدمات ←</a></div></section>
<section className="stats wrap">{[["واحد","ممارس أقدم"],["واضح","النطاق"],["ثابتة","الأتعاب"],["عملي","المخرَج"]].map(x=><article key={x[1]}><strong>{x[0]}</strong><code>{x[1]}</code></article>)}</section>
<section id="plain" className="section wrap split"><div><Eye>§ ٠١ · بعبارة بسيطة</Eye><h2>عمل مالي يبدو بسيطًا، حتى حين لا تكون المسألة كذلك.</h2></div><div className="prose"><p>دفتر — <em>دَفْتَر</em>، السجلّ أو القيد — يساعد الشركات على تجهيز أرقامها للتدقيق والمجالس والمقرضين والمستثمرين والقرارات المهمة.</p><p>كل ذلك دون كلفة وتعقيد شركة استشارية كبيرة. ممارس أقدم واحد، نطاق واضح، أتعاب ثابتة، ومخرَج عملي يبقى في يد فريقك.</p></div></section>
<section id="services" className="section soft"><div className="wrap"><Eye>§ ٠٢ · الخدمات</Eye><h2>أربع خدمات جوهرية. كلٌّ تنتهي بمخرَج واضح.</h2><div className="practice-list">{services.map(x=><article key={x[0]}><code>{x[0]}</code><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section id="fit" className="section wrap"><Eye>§ ٠٣ · ما يجعله أيسر</Eye><h2>مبنيّ للمؤسّسين والمدراء الماليين والفرق الصغيرة.</h2><div className="grid four principles">{fit.map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section className="handoff"><div className="wrap split"><div><Eye>كاليبر · من دفتر</Eye><h2>الصرامة نفسها، موجَّهة إلى التوظيف المالي.</h2></div><div><p>حُكم كاليبر هو مذكّرة دفتر لقرار توظيف دور مالي واحد: نقرأ القائمة القصيرة ونقيّمها ونعايِرها لنسلّمك توصية واحدة قابلة للدفاع.</p><Link className="button light" href="/ar/calibre">استكشف كاليبر ←</Link></div></div></section>
<section id="scope" className="scope"><div className="wrap"><div className="scope-intro"><Eye>§ ٠٤ · ابدأ</Eye><h2>لنجعل الرقم القادم <em>واضحًا</em>.</h2><p className="lead">أخبِرنا بما هو مطروح — قوائم مالية، أو تدقيق قادم، أو مسألة محاسبية. سنخبرك بصراحة إن كنّا نستطيع المساعدة، عادةً خلال يومَي عمل.</p><div className="contact"><a href={email}>ahmad@daftaradvisory.com</a> · عمّان · المنطقة</div></div><form className="scope-form" name="daftar-scope" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/ar?scoped=daftar"><input type="hidden" name="form-name" value="daftar-scope"/><p className="scope-hp"><label>اتركه فارغًا <input name="bot-field"/></label></p><div className="row"><div className="field"><label htmlFor="a-name">الاسم</label><input id="a-name" name="name" required/></div><div className="field"><label htmlFor="a-email">البريد الإلكتروني</label><input id="a-email" name="email" type="email" required/></div></div><div className="field"><label htmlFor="a-org">المؤسسة</label><input id="a-org" name="organisation"/></div><div className="field"><label htmlFor="a-decision">ما المسألة المالية المطروحة؟</label><textarea id="a-decision" name="decision"/></div><div className="field"><label htmlFor="a-time">الإطار الزمني</label><select id="a-time" name="timeline" defaultValue=""><option value="" disabled>اختر…</option><option>استكشاف مبدئي</option><option>هذا الربع</option><option>عاجل</option></select></div><div className="form-actions"><button className="button" type="submit">ابدأ محادثة</button><p className="note">قراءة أقدم لما إن كنّا نستطيع المساعدة — وكيف.</p></div></form></div></section>
<footer><Mark/><em className="foot-tag">تمويل صارم، دون العبء الإضافي.</em><div><Link href="/ar/calibre">كاليبر</Link><a href="mailto:ahmad@daftaradvisory.com">AHMAD@DAFTARADVISORY.COM</a><span>عمّان · المنطقة</span></div></footer></main>}
