import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "دفتر للاستشارات",
  description: "ممارسة استشارية مستقلة للقادة الذين يواجهون قرارات ذات وزن مالي وتنظيمي وسمعوي.",
};

const email="mailto:ahmad@daftaradvisory.com?subject=محادثة%20مع%20دفتر";
const practices=[["٠١","هندسة القرار","نجعل الخيارات المعقّدة مقروءة — بتحديد السؤال، واختبار الافتراضات، وترك سجلّ واضح لسبب صمود القرار."],["٠٢","الوضوح المالي","نترجم الأرقام إلى رؤية عملية للأعمال، من جاهزية الاستثمار وقرارات رأس المال إلى التقارير والرقابة."],["٠٣","الحُكم المؤسسي","نقوّي الأنظمة التي تقيّم بها الفرق الأشخاص، وتوزّع المسؤولية، وتتّخذ القرارات المصيرية."]];
const principles=[["الأقدمية افتراضيًا","فرق صغيرة، وصول مباشر، خبرة راسخة."],["الدليل قبل العرض","يجب أن يصمد العمل أمام التدقيق، لا أن يُقدَّم فحسب."],["أدوات تبقى","كل مهمة تترك في يدك نموذجًا أو منهجًا أو مذكرة."],["طلاقة إقليمية","مبنيّة للأردن والخليج ومنطقة الشرق الأوسط الأوسع."]];
function Mark(){return <Link className="brand daftar-brand" href="/ar"><b>D</b><span><em>دفتر</em><small>للاستشارات</small></span></Link>}
function Eye({children}:{children:React.ReactNode}){return <div className="eyebrow chapter"><i/>{children}</div>}
export default function DaftarAr(){return <main className="daftar ar" dir="rtl" lang="ar"><header><Mark/><nav><a href="#story">قصة الشركة</a><a href="#practice">الممارسة</a><a href="#principles">المبادئ</a><Link href="/ar/calibre">كاليبر</Link><Link href="/" className="lang" aria-label="English">EN</Link><a className="button small" href="#scope">ابدأ محادثة</a></nav><a className="menu" href="#story">☰</a></header>
<section className="hero wrap daftar-hero"><div><Eye>§ ٠٠ · الشركة</Eye><h1>القرارات الجيدة تستحقّ أن تُكتب.</h1><p className="lead">دفتر ممارسة استشارية مستقلة للقادة الذين يواجهون قرارات ذات وزن مالي وتنظيمي وسُمعوي.</p><a className="text-link" href="#story">اقرأ قصتنا ←</a></div></section>
<section className="stats wrap">{[["٢٠٢٤","سنة التأسيس"],["الخليج","المنطقة"],["٠٣","خطوط الممارسة"],["كاليبر","أول منتج"]].map(x=><article key={x[1]}><strong>{x[0]}</strong><code>{x[1]}</code></article>)}</section>
<section id="story" className="section wrap split"><div><Eye>§ ٠١ · قصة الشركة</Eye><h2>يجب أن تبقى المشورة نافعة بعد رحيل المستشار.</h2></div><div className="prose"><p>دفتر — <em>دَفْتَر</em>، السجلّ أو القيد — سُمّيت باسم الانضباط الجوهري للممارسة: كتابة القرارات بصيغة تصمد.</p><p>أسّسنا الشركة لخدمة القادة في الأردن والخليج والمنطقة الأوسع ممّن سئموا مشورةً تتبخّر بانتهاء المهمة. نعمل في فِرق صغيرة أقدم، وكل مهمة تترك أثرًا عمليًا — نموذجًا أو منهجًا أو مذكرة — لا مجلّدًا يُركَن على رفّ.</p><p>مهمتنا أن نجعل تفكيرك مقروءًا: لك، ولمجلسك، ولمن يرث القرار من بعدك.</p></div></section>
<section id="practice" className="section soft"><div className="wrap"><Eye>§ ٠٢ · الممارسة</Eye><h2>ثلاثة خطوط عمل. انضباط واحد.</h2><div className="practice-list">{practices.map(x=><article key={x[0]}><code>{x[0]}</code><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section id="principles" className="section wrap"><Eye>§ ٠٣ · المبادئ</Eye><h2>كيف نختار أن نعمل.</h2><div className="grid four principles">{principles.map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section className="handoff"><div className="wrap split"><div><Eye>كاليبر · من دفتر</Eye><h2>الصرامة نفسها، موجَّهة إلى التوظيف.</h2></div><div><p>كاليبر هو أداة دفتر التشخيصية لقرارات التوظيف: منهج منظّم يساعد الفرق على قراءة المرشّحين وتقييمهم ومقارنتهم ومعايرتهم وفق معيار واحد مشترك.</p><Link className="button light" href="/ar/calibre">استكشف كاليبر ←</Link></div></div></section>
<section id="scope" className="scope"><div className="wrap"><div className="scope-intro"><Eye>§ ٠٤ · ابدأ</Eye><h2>اجعل القرار القادم <em>مقروءًا</em>.</h2><p className="lead">أخبِرنا بما هو مطروح. سنخبرك بصراحة إن كنّا نستطيع المساعدة — عادةً خلال يومَي عمل.</p><div className="contact"><a href={email}>ahmad@daftaradvisory.com</a> · عمّان · المنطقة</div></div><form className="scope-form" name="daftar-scope" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/ar?scoped=daftar"><input type="hidden" name="form-name" value="daftar-scope"/><p className="scope-hp"><label>اتركه فارغًا <input name="bot-field"/></label></p><div className="row"><div className="field"><label htmlFor="a-name">الاسم</label><input id="a-name" name="name" required/></div><div className="field"><label htmlFor="a-email">البريد الإلكتروني</label><input id="a-email" name="email" type="email" required/></div></div><div className="field"><label htmlFor="a-org">المؤسسة</label><input id="a-org" name="organisation"/></div><div className="field"><label htmlFor="a-decision">ما القرار المطروح؟</label><textarea id="a-decision" name="decision"/></div><div className="field"><label htmlFor="a-time">الإطار الزمني</label><select id="a-time" name="timeline" defaultValue=""><option value="" disabled>اختر…</option><option>استكشاف مبدئي</option><option>هذا الربع</option><option>عاجل</option></select></div><div className="form-actions"><button className="button" type="submit">ابدأ محادثة</button><p className="note">قراءة أقدم لما إن كنّا نستطيع المساعدة — وكيف.</p></div></form></div></section>
<footer><Mark/><em className="foot-tag">تمويل صارم، دون العبء الإضافي.</em><div><Link href="/ar/calibre">كاليبر</Link><a href="mailto:ahmad@daftaradvisory.com">AHMAD@DAFTARADVISORY.COM</a><span>عمّان · المنطقة</span></div></footer></main>}
