import Link from "next/link";
const email="mailto:ahmad@daftaradvisory.com?subject=Daftar%20Advisory%20conversation";
const practices=[["01","Decision architecture","We make complex choices legible — defining the question, testing assumptions, and leaving a clear record of why the decision holds."],["02","Financial clarity","We translate numbers into a working view of the business, from investment readiness and capital decisions to reporting and control."],["03","Organisational judgment","We strengthen the systems through which teams assess people, allocate responsibility, and make consequential calls."]];
const principles=[["Senior by default","Small teams, direct access, experienced judgment."],["Evidence before theatre","The work must survive scrutiny, not just presentation."],["Artifacts that remain","Every engagement leaves a model, method, or memo in your hands."],["Regional fluency","Built for Jordan, the GCC, and the wider MENA context."]];
function Mark(){return <Link className="brand daftar-brand" href="/daftar"><b>D</b><span><em>Daftar</em><small>ADVISORY</small></span></Link>}
function Eye({children}:{children:React.ReactNode}){return <div className="eyebrow chapter"><i/>{children}</div>}
export default function Daftar(){return <main className="daftar"><header><Mark/><nav><a href="#story">Firm story</a><a href="#practice">Practice</a><a href="#principles">Principles</a><Link href="/">Calibre</Link><a className="button small" href={email}>Start a conversation</a></nav><a className="menu" href="#story">☰</a></header>
<section className="hero wrap daftar-hero"><div><Eye>§ 00 · The firm</Eye><h1>Good decisions deserve to be written down.</h1><p className="lead">Daftar is an independent advisory practice for leaders navigating decisions that carry financial, organisational, and reputational weight.</p><a className="text-link" href="#story">Read our story →</a></div></section>
<section className="stats wrap">{[["2024","Established"],["MENA","Region"],["03","Practice lines"],["Calibre","First product"]].map(x=><article key={x[1]}><strong>{x[0]}</strong><code>{x[1]}</code></article>)}</section>
<section id="story" className="section wrap split"><div><Eye>§ 01 · Firm story</Eye><h2>Advice should remain useful after the adviser leaves.</h2></div><div className="prose"><p>Daftar — <em>daf·tar</em>, the ledger or register — is named for the discipline at the heart of the practice: writing decisions down in a form that holds up.</p><p>We founded the firm to serve leaders across Jordan, the GCC, and the wider MENA region who are tired of advice that evaporates when the engagement ends. We work in small, senior teams. Every engagement leaves a working artifact — a model, a method, a memo — not a binder that goes on a shelf.</p><p>Our job is to make your reasoning legible: to you, to your board, and to whoever inherits the decision after you.</p></div></section>
<section id="practice" className="section soft"><div className="wrap"><Eye>§ 02 · The practice</Eye><h2>Three lines of work. One discipline.</h2><div className="practice-list">{practices.map(x=><article key={x[0]}><code>{x[0]}</code><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section id="principles" className="section wrap"><Eye>§ 03 · Principles</Eye><h2>How we choose to work.</h2><div className="grid four principles">{principles.map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section className="handoff"><div className="wrap split"><div><Eye>Calibre · by Daftar</Eye><h2>The same rigor, turned on hiring.</h2></div><div><p>Calibre is Daftar&apos;s hiring-decision diagnostic: a structured method that helps teams read, score, compare, and calibrate candidates against one shared standard.</p><Link className="button light" href="/">Explore Calibre →</Link></div></div></section>
<section className="cta"><h2>Make the next decision legible.</h2><p>Tell us what is on the table. We will tell you, plainly, whether we can help.</p><a className="button" href={email}>Start a conversation</a></section>
<footer><Mark/><div><Link href="/">CALIBRE</Link><a href="mailto:ahmad@daftaradvisory.com">AHMAD@DAFTARADVISORY.COM</a><span>AMMAN · MENA</span></div></footer></main>}
