import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Calibre Verdict — by Daftar",
  description: "A done-for-you finance-hiring decision memo. Read, score, compare, calibrate — one defensible recommendation in two weeks.",
};

const email="mailto:ahmad@daftaradvisory.com?subject=Calibre%20Verdict";
const method=[
  ["Read","We read the shortlist you've already sourced — CVs, work history, and the finance context the role sits in."],
  ["Score","Each candidate is scored against a role-specific rubric, so judgment becomes comparable, defensible evidence."],
  ["Compare","Scores line up side by side, and the real disagreement surfaces before an offer — not after."],
  ["Calibrate","We resolve the gaps into one ranked recommendation the whole panel can stand behind."],
];
const deliverables=[
  ["Role-specific scorecard","Weighted criteria built for the exact finance role — controller, finance manager, first hire, or FP&A lead."],
  ["Candidate-reading guide","What strong, adequate, and weak answers look like for this role, so every reviewer reads the same signal."],
  ["Interview question bank","Questions mapped to each criterion, with follow-ups that pressure-test the finance signal."],
  ["Ranked decision memo","One written recommendation with the reasoning — the defensible record you put in the file."],
  ["Hiring-risk notes","Where the evidence is thin, where the panel disagreed, and what to probe before an offer."],
  ["Outcome register","Post-decision tracking of the hire — the evidence base that makes the next Verdict sharper."],
];
const scope=[
  ["One finance role","A single finance-function role per Verdict — controller, finance manager, first finance hire, or FP&A lead."],
  ["Your shortlist","A named shortlist you've already sourced — typically three to six candidates."],
  ["What we review","CVs, work history, and the evidence in front of the panel, scored against the rubric."],
  ["Two weeks, fixed","A fixed-fee, fixed-scope engagement that ends in the decision memo."],
];
const faqs=[
  ["Is this recruitment?","No. You source the shortlist; Calibre evaluates it. We don't place candidates or negotiate offers — we hand you a defensible decision."],
  ["Why only finance roles?","Because the evaluation rests on finance judgment — the same rigour Daftar brings to the numbers, turned on the people who will own them."],
  ["We already use DISC or psychometrics.","Those describe personality. Calibre installs a structured evaluation of the actual role — it complements psychometrics, it doesn't compete with them."],
  ["Isn't assessing candidates a legal risk?","Calibre structures how your panel evaluates, not a personality test on candidates. It's job-relevant and documented — built to make the decision more defensible, not less."],
  ["How long does it take?","Two weeks for one role, from scoping to the decision memo. Timeline and fee are fixed before we start."],
  ["Where does it fit?","Most often alongside a Daftar finance engagement, when a finance hire is on the table. It can also be run on its own."],
];

function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><i/>§ {children}</div>}
function Brand(){return <Link className="brand" href="/calibre"><b>C</b><span><em>Calibre</em><small>BY DAFTAR</small></span></Link>}

export default function Calibre(){return <main className="calibre">
  <header><Brand/><nav><a href="#method">Method</a><a href="#deliver">The memo</a><a href="#scope-of-work">Scope</a><a href="#who">Who it&apos;s for</a><a href="#faq">FAQ</a><Link href="/">Daftar</Link><Link href="/ar/calibre" className="lang" aria-label="العربية">ع</Link><a className="button small" href="#scope">Request a Verdict</a></nav><a className="menu" href="#method" aria-label="Open navigation">☰</a></header>
  <section className="hero wrap"><div><Eyebrow>The Calibre Verdict</Eyebrow><h1>Your most important finance hire, decided on evidence.</h1><p className="lead">The Calibre Verdict is a done-for-you decision memo for a single finance role. We read the shortlist you&apos;ve sourced, score it against a role-specific rubric, and hand you one ranked, defensible recommendation — in two weeks.</p><div className="actions"><a className="button" href="#scope">Request a Verdict</a><a className="text-link" href="#method">See how it works →</a></div></div><Scorecard/></section>
  <section className="cred"><div className="wrap"><article><Eyebrow>Who builds it</Eyebrow><h3>Finance evaluation from the Big-4 and executive-search side of the table — turned on your own hire.</h3><p>Built by Ahmad Al Hinaiti, Founder of Daftar Advisory.</p></article><article><Eyebrow>Where it fits</Eyebrow><h3>Offered alongside Daftar&apos;s finance engagements.</h3><p>Jordan, the UAE, and the wider region — wherever a finance hire has to be defensible.</p></article></div></section>
  <section className="dark"><div className="wrap problem"><div><Eyebrow>The problem</Eyebrow><h2>Same shortlist.<br/>Four reviewers.<br/>Four verdicts.</h2><p>Even a finance hire often runs on gut feel dressed up as judgment. Without a shared standard, the score drifts with the reviewer — not the candidate — and no one can say, afterwards, why the appointment was made.</p></div><ReviewerCard/></div></section>
  <section id="method" className="section wrap"><Eyebrow>The Calibre method</Eyebrow><h2>Four steps from opinion to evidence.</h2><div className="grid four">{method.map((x,i)=><article className="method" key={x[0]}><code>{String(i+1).padStart(2,"0")}</code><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
  <section id="deliver" className="section soft"><div className="wrap"><Eyebrow>What you receive</Eyebrow><h2>A scorecard and a ranked memo — not a slide deck.</h2><div className="grid three">{deliverables.map((x,i)=><article className="card" key={x[0]}><code>{String(i+1).padStart(2,"0")}</code><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section id="scope-of-work" className="section wrap"><Eyebrow>What&apos;s in scope</Eyebrow><h2>One role. One shortlist. One <em>verdict</em>.</h2><div className="grid four">{scope.map((x,i)=><article className="method" key={x[0]}><code>{String(i+1).padStart(2,"0")}</code><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><p className="scope-note">Sourcing, offer negotiation, and the hiring decision itself stay yours. You decide; Calibre calibrates.</p></section>
  <section id="who" className="section soft"><div className="wrap who"><div><Eyebrow>Who it&apos;s for</Eyebrow><h2>For anyone who owns a finance appointment they&apos;ll have to defend.</h2></div><div className="people">{[["Founders","Your first finance hire sets the tone — make it on evidence."],["CFOs & finance leaders","A defensible read on the person who&apos;ll own your numbers."],["Boards & investors","Confidence a key finance appointment was made on more than a hunch."],["Lean finance teams","A senior second opinion when the panel disagrees."]].map(x=><article key={x[0]}><h3><em>{x[0]}</em></h3><p>{x[1]}</p></article>)}</div></div></section>
  <section id="pilot" className="pilot"><div className="wrap"><Eyebrow>How a Verdict runs</Eyebrow><div className="pilot-grid"><div><h2>One role. Two weeks. A decision you can defend.</h2><p>Bring one finance role and the shortlist you&apos;ve sourced. We run it end-to-end through a short, fixed-scope engagement and hand back the memo.</p><code>ONE FINANCE ROLE · 2 WEEKS · FIXED FEE</code></div><div>{[["Scope the role","Define the criteria and weightings for the finance role with you."],["Read & score","Each shortlisted candidate scored independently against the shared rubric."],["Compare & calibrate","Turn four reads into one ranked, defensible decision."],["Decision memo","You keep the scorecard, the memo, and the outcome register."]].map((x,i)=><article className="pilot-step" key={x[0]}><code>{String(i+1).padStart(2,"0")}</code><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></div></div></section>
  <section className="benefits wrap">{[["Clearer","Everyone knows what “good” means for the role before the first interview."],["Faster","Less circular debate; the decision lands in days, not weeks."],["More consistent","The same standard across every reviewer on the panel."],["More defensible","A documented rationale you can put in the file and stand behind."]].map(x=><article key={x[0]}><em>{x[0]}</em><p>{x[1]}</p></article>)}</section>
  <section id="faq" className="section soft"><div className="wrap faq"><div><Eyebrow>Common questions</Eyebrow><h2>Before you request a Verdict.</h2></div><div>{faqs.map((x,i)=><article key={x[0]}><code>{String(i+1).padStart(2,"0")}</code><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></div></section>
  <section id="scope" className="scope"><div className="wrap"><div className="scope-intro"><Eyebrow>Request a Verdict</Eyebrow><h2>Bring one finance role to <em>Calibre</em>.</h2><p className="lead">Tell us the role and where the shortlist stands; we reply within two working days.</p><div className="contact"><a href={email}>ahmad@daftaradvisory.com</a></div></div><form className="scope-form" name="calibre-scope" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/calibre?scoped=calibre"><input type="hidden" name="form-name" value="calibre-scope"/><p className="scope-hp"><label>Leave this empty <input name="bot-field"/></label></p><div className="row"><div className="field"><label htmlFor="c-name">Name</label><input id="c-name" name="name" required/></div><div className="field"><label htmlFor="c-email">Work email</label><input id="c-email" name="email" type="email" required/></div></div><div className="field"><label htmlFor="c-company">Company</label><input id="c-company" name="company"/></div><div className="row"><div className="field"><label htmlFor="c-role">Finance role you&apos;re hiring</label><select id="c-role" name="finance_role" defaultValue=""><option value="" disabled>Select…</option><option>Financial controller</option><option>Finance manager</option><option>First finance hire</option><option>FP&amp;A lead</option><option>Other finance role</option></select></div><div className="field"><label htmlFor="c-short">Shortlist stage</label><select id="c-short" name="shortlist" defaultValue=""><option value="" disabled>Select…</option><option>Shortlist ready (3–6)</option><option>Still shortlisting</option><option>Not yet sourced</option></select></div></div><div className="field"><label htmlFor="c-notes">What&apos;s the decision you&apos;re weighing?</label><textarea id="c-notes" name="notes"/></div><div className="form-actions"><button className="button" type="submit">Request a Verdict</button><p className="note">One role, fixed scope. No obligation beyond the call.</p></div></form></div></section>
  <footer><Brand/><div><Link href="/">ABOUT DAFTAR</Link><a href="mailto:ahmad@daftaradvisory.com">AHMAD@DAFTARADVISORY.COM</a><span>DAFTARADVISORY.COM</span></div></footer>
  </main>}

function Scorecard(){const rows=[["Technical depth",82,"4.1"],["Controls & rigour",64,"3.2"],["Business partnering",90,"4.5"]];return <article className="scorecard"><div className="score-head"><code>SCORECARD · GROUP FINANCIAL CONTROLLER</code><code>CAND. #04</code></div>{rows.map(x=><div className="score-row" key={String(x[0])}><span>{x[0]}</span><i><b style={{width:`${x[1]}%`}}/></i><code>{x[2]}</code></div>)}<div className="total"><em>Weighted total</em><strong>3.9</strong></div></article>}
function ReviewerCard(){return <article className="review-card"><code>CANDIDATE #04 · UNCALIBRATED</code>{[["A",85,"8.5"],["B",50,"5.0"],["C",75,"7.5"],["D",30,"3.0"]].map(x=><div className="review" key={x[0]}><code>REV. {x[0]}</code><i><b style={{width:`${x[1]}%`}}/></i><code>{x[2]}</code></div>)}<div className="spread"><em>Spread</em><code>5.5 points</code></div></article>}
